name: Build-OpenWrt-ImmortalWrt-b1

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 3 * * 0,2,3,5,6'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #      - name: Maximize build space
      #        uses: easimon/maximize-build-space@master
      #        with:
      #          root-reserve-mb: 512
      #          swap-size-mb: 1024
      #          remove-dotnet: 'true'

      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Install Dependency
        run: |
          docker rmi $(docker images -q)
          sudo apt-get -qq remove --purge azure-cli ghc zulu* hhvm llvm* firefox google* \
          dotnet* powershell mysql* php* mssql-tools msodbcsql17 android*
          sudo apt-get install -qq -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib \
            git git-core gperf haveged help2man intltool lib32gcc1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev \
            libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncurses5-dev libreadline-dev libssl-dev libtool libz-dev \
            lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip python3-ply \
            python-docutils qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim \
            wget xmlto xxd zlib1g-dev
          sudo apt-get -qq autoremove --purge
          sudo apt-get -qq clean
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android

      - name: Clone
        run: |
          chmod +x clone_source.sh && ./clone_source.sh

      - name: Build
        run: |
          echo "Free space:"
          df -h
          cp .config_immortalwrt ./immortalwrt/.config && cp before_build.sh ./immortalwrt/before_build.sh
          cd immortalwrt
          chmod +x before_build.sh && ./before_build.sh
          ./scripts/feeds update -a && ./scripts/feeds install -a
          make defconfig
          make -j8 download
          make -j$(($(nproc) + 1)) V=s

      - name: Upload Packages
        uses: actions/upload-artifact@v2
        with:
          name: Packages-$(date +%Y%m%d%H%M)
          path: ./bin/packages/

      - name: Upload Firmwares
        uses: actions/upload-artifact@v2
        with:
          name: ImmortalWrt-Newifi3-d2-$(date +%Y%m%d%H%M)
          path: ./bin/targets/