name: Build-OpenWrt-ImmortalWrt-b2

on:
  push:
    branches:
      - b2
  workflow_dispatch:
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron: '0 15 * * 1,2,4,5,6'
jobs:
  build:
    runs-on: ubuntu-latest #ubuntu-18.04

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: apt-get remove
        run: |
          docker rmi $(docker images -q)
          sudo apt-get -qq remove --purge azure-cli ghc zulu* hhvm llvm* firefox google* \
          dotnet* powershell mysql* php* mssql-tools msodbcsql17 android*
          sudo apt-get -qq autoremove --purge
          sudo apt-get -qq clean
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android
      - name: GHCR
        uses: docker://ghcr.io/ibook86/docker-openwrt-build:main
